---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels: 
    app: db-deployment
  namespace: vote

spec:
  selector:
    matchLabels:
      app: db-deployment
  template:
    containers:
      - image: postgres:9.4
        name: postgres-db
        env:
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
        volumeMounts:
          - name: db-data
            mountPath: /var/lib/postgresql/data
    volumes:
      - name: db-data
        emptyDir: {}