---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
  namespace: vote

spec:
  selector:
    matchLabels:
      app: worker
  
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - image: kodekloud/examplevotingapp_worker
          name: examplevotingapp-worker